export const courses = [
  {
    title: "Javascript",
    titleSlug: "javascript",
    description:
      "JavaScript (JS) is a versatile and dynamic programming language primarily used for enhancing the interactivity of web pages. Developed initially as a client-side scripting language for web browsers, JS has evolved into a ubiquitous language capable of running on both client and server sides through frameworks like Node.js",
    chapters: [
      {
        title: "Introduction to JavaScript",
        titleSlug: "introduction-to-javascript",
        status: "active",
        topics: 8,
        courseName: "Javascript",
      },
      {
        title: "Data Types and Variables",
        titleSlug: "data-types-and-variables",
        status: "active",
        topics: 7,
        courseName: "Javascript",
      },
      {
        title: "Functions and Scope",
        titleSlug: "functions-and-scope",
        status: "active",
        topics: 6,
        courseName: "Javascript",
      },
      {
        title: "Objects and Prototypes",
        titleSlug: "objects-and-prototypes",
        status: "active",
        topics: 9,
        courseName: "Javascript",
      },
      {
        title: "ES6 Features",
        titleSlug: "es6-features",
        status: "active",
        topics: 7,
        courseName: "Javascript",
      },
    ],
    status: "active",
  },
  {
    title: "Python",
    titleSlug: "python",
    description:
      "Python is a high-level, interpreted programming language known for its readability and ease of use. It supports multiple programming paradigms, including procedural, object-oriented, and functional programming.",
    chapters: [
      {
        title: "Python Basics",
        titleSlug: "python-basics",
        status: "active",
        topics: 9,
        courseName: "Python",
      },
      {
        title: "Functions and Modules",
        titleSlug: "functions-and-modules",
        status: "active",
        topics: 6,
        courseName: "Python",
      },
      {
        title: "Data Structures",
        titleSlug: "data-structures",
        status: "active",
        topics: 8,
        courseName: "Python",
      },
      {
        title: "Object-Oriented Programming",
        titleSlug: "object-oriented-programming",
        status: "active",
        topics: 7,
        courseName: "Python",
      },
      {
        title: "File Handling",
        titleSlug: "file-handling",
        status: "active",
        topics: 6,
        courseName: "Python",
      },
    ],
    status: "active",
  },
  {
    title: "React",
    titleSlug: "react",
    description:
      "React is a JavaScript library for building user interfaces, developed by Facebook. It allows developers to create large web applications that can update and render efficiently in response to data changes.",
    chapters: [
      {
        title: "Getting Started with React",
        titleSlug: "getting-started-with-react",
        status: "active",
        topics: 10,
        courseName: "React",
      },
      {
        title: "Components and Props",
        titleSlug: "components-and-props",
        status: "active",
        topics: 7,
        courseName: "React",
      },
      {
        title: "State and Lifecycle",
        titleSlug: "state-and-lifecycle",
        status: "active",
        topics: 8,
        courseName: "React",
      },
      {
        title: "Handling Events",
        titleSlug: "handling-events",
        status: "active",
        topics: 6,
        courseName: "React",
      },
    ],
    status: "active",
  },
  {
    title: "Node.js",
    titleSlug: "nodejs",
    description:
      "Node.js is a runtime environment that allows developers to use JavaScript for server-side scripting, running scripts server-side to produce dynamic web page content before the page is sent to the user’s web browser.",
    chapters: [
      {
        title: "Introduction to Node.js",
        titleSlug: "introduction-to-nodejs",
        status: "active",
        topics: 6,
        courseName: "Node.js",
      },
      {
        title: "Modules and NPM",
        titleSlug: "modules-and-npm",
        status: "active",
        topics: 8,
        courseName: "Node.js",
      },
      {
        title: "Express.js Framework",
        titleSlug: "expressjs-framework",
        status: "active",
        topics: 9,
        courseName: "Node.js",
      },
      {
        title: "RESTful APIs",
        titleSlug: "restful-apis",
        status: "active",
        topics: 7,
        courseName: "Node.js",
      },
    ],
    status: "active",
  },
  {
    title: "Django",
    titleSlug: "django",
    description:
      "Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design. It provides a high-level of abstraction of common patterns, enabling developers to focus on writing the unique parts of their applications.",
    chapters: [
      {
        title: "Getting Started with Django",
        titleSlug: "getting-started-with-django",
        status: "inactive",
        topics: 7,
        courseName: "Django",
      },
      {
        title: "Models and Migrations",
        titleSlug: "models-and-migrations",
        status: "inactive",
        topics: 6,
        courseName: "Django",
      },
      {
        title: "Views and Templates",
        titleSlug: "views-and-templates",
        status: "inactive",
        topics: 8,
        courseName: "Django",
      },
      {
        title: "Forms and Admin Interface",
        titleSlug: "forms-and-admin-interface",
        status: "inactive",
        topics: 6,
        courseName: "Django",
      },
      {
        title: "Django REST Framework",
        titleSlug: "django-rest-framework",
        status: "inactive",
        topics: 9,
        courseName: "Django",
      },
    ],
    status: "inactive",
  },
  {
    title: "Flask",
    titleSlug: "flask",
    description:
      "Flask is a micro web framework written in Python. It is designed to be simple and easy to use, allowing developers to create web applications quickly.",
    chapters: [
      {
        title: "Introduction to Flask",
        titleSlug: "introduction-to-flask",
        status: "active",
        topics: 6,
        courseName: "Flask",
      },
      {
        title: "Routing and Views",
        titleSlug: "routing-and-views",
        status: "active",
        topics: 7,
        courseName: "Flask",
      },
      {
        title: "Templates and Forms",
        titleSlug: "templates-and-forms",
        status: "active",
        topics: 8,
        courseName: "Flask",
      },
      {
        title: "Database Integration",
        titleSlug: "database-integration",
        status: "active",
        topics: 9,
        courseName: "Flask",
      },
    ],
    status: "active",
  },
  {
    title: "Angular",
    titleSlug: "angular",
    description:
      "Angular is a platform and framework for building single-page client applications using HTML and TypeScript. It is maintained by Google and a community of individuals and corporations.",
    chapters: [
      {
        title: "Getting Started with Angular",
        titleSlug: "getting-started-with-angular",
        status: "inactive",
        topics: 7,
        courseName: "Angular",
      },
      {
        title: "Components and Directives",
        titleSlug: "components-and-directives",
        status: "inactive",
        topics: 8,
        courseName: "Angular",
      },
      {
        title: "Services and Dependency Injection",
        titleSlug: "services-and-dependency-injection",
        status: "inactive",
        topics: 9,
        courseName: "Angular",
      },
      {
        title: "Routing and Navigation",
        titleSlug: "routing-and-navigation",
        status: "inactive",
        topics: 6,
        courseName: "Angular",
      },
      {
        title: "Angular CLI and Testing",
        titleSlug: "angular-cli-and-testing",
        status: "inactive",
        topics: 6,
        courseName: "Angular",
      },
    ],
    status: "inactive",
  },
  {
    title: "Vue.js",
    titleSlug: "vuejs",
    description:
      "Vue.js is an open-source model–view–viewmodel front end JavaScript framework for building user interfaces and single-page applications. It is designed to be incrementally adoptable.",
    chapters: [
      {
        title: "Introduction to Vue.js",
        titleSlug: "introduction-to-vuejs",
        status: "active",
        topics: 8,
        courseName: "Vue.js",
      },
      {
        title: "Vue Components and Props",
        titleSlug: "vue-components-and-props",
        status: "active",
        topics: 7,
        courseName: "Vue.js",
      },
      {
        title: "Vue Router and Vuex",
        titleSlug: "vue-router-and-vuex",
        status: "active",
        topics: 9,
        courseName: "Vue.js",
      },
      {
        title: "Advanced Vue.js Concepts",
        titleSlug: "advanced-vuejs-concepts",
        status: "active",
        topics: 6,
        courseName: "Vue.js",
      },
    ],
    status: "active",
  },
  {
    title: "Java",
    titleSlug: "java",
    description:
      "Java is a general-purpose, class-based, object-oriented programming language designed to have as few implementation dependencies as possible. It is intended to let application developers write once, run anywhere (WORA), meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.",
    chapters: [
      {
        title: "Java Basics",
        titleSlug: "java-basics",
        status: "active",
        topics: 10,
        courseName: "Java",
      },
      {
        title: "Object-Oriented Programming in Java",
        titleSlug: "object-oriented-programming-in-java",
        status: "active",
        topics: 8,
        courseName: "Java",
      },
      {
        title: "Collections Framework",
        titleSlug: "collections-framework",
        status: "active",
        topics: 9,
        courseName: "Java",
      },
      {
        title: "Concurrency in Java",
        titleSlug: "concurrency-in-java",
        status: "active",
        topics: 7,
        courseName: "Java",
      },
    ],
    status: "active",
  },
  {
    title: "C#",
    titleSlug: "csharp",
    description:
      "C# (pronounced see sharp) is a general-purpose, multi-paradigm programming language encompassing strong typing, lexically scoped, imperative, declarative, functional, generic, object-oriented (class-based), and component-oriented programming disciplines. It was developed around 2000 by Microsoft as part of its .NET initiative.",
    chapters: [
      {
        title: "Introduction to C#",
        titleSlug: "introduction-to-csharp",
        status: "inactive",
        topics: 8,
        courseName: "C#",
      },
      {
        title: "C# Basics",
        titleSlug: "csharp-basics",
        status: "inactive",
        topics: 7,
        courseName: "C#",
      },
      {
        title: "Advanced C# Programming",
        titleSlug: "advanced-csharp-programming",
        status: "inactive",
        topics: 9,
        courseName: "C#",
      },
      {
        title: "ASP.NET Core",
        titleSlug: "aspnet-core",
        status: "inactive",
        topics: 6,
        courseName: "C#",
      },
    ],
    status: "inactive",
  },
  {
    title: "Ruby on Rails",
    titleSlug: "ruby-on-rails",
    description:
      "Ruby on Rails, or Rails, is a server-side web application framework written in Ruby under the MIT License. Rails is a model–view–controller (MVC) framework, providing default structures for a database, a web service, and web pages.",
    chapters: [
      {
        title: "Getting Started with Ruby on Rails",
        titleSlug: "getting-started-with-ruby-on-rails",
        status: "active",
        topics: 7,
        courseName: "Ruby on Rails",
      },
      {
        title: "Rails Models and Controllers",
        titleSlug: "rails-models-and-controllers",
        status: "active",
        topics: 8,
        courseName: "Ruby on Rails",
      },
      {
        title: "Views and Layouts in Rails",
        titleSlug: "views-and-layouts-in-rails",
        status: "active",
        topics: 9,
        courseName: "Ruby on Rails",
      },
      {
        title: "RESTful APIs with Rails",
        titleSlug: "restful-apis-with-rails",
        status: "active",
        topics: 6,
        courseName: "Ruby on Rails",
      },
    ],
    status: "active",
  },
  {
    title: "PHP",
    titleSlug: "php",
    description:
      "PHP is a server-side scripting language designed primarily for web development, but it is also used as a general-purpose programming language. PHP code is executed on the server, generating HTML content that is then sent to the client's web browser.",
    chapters: [
      {
        title: "PHP Basics",
        titleSlug: "php-basics",
        status: "inactive",
        topics: 6,
        courseName: "PHP",
      },
      {
        title: "PHP Functions and Arrays",
        titleSlug: "php-functions-and-arrays",
        status: "inactive",
        topics: 7,
        courseName: "PHP",
      },
      {
        title: "MySQL Database Integration",
        titleSlug: "mysql-database-integration",
        status: "inactive",
        topics: 8,
        courseName: "PHP",
      },
      {
        title: "Building Web Applications with PHP",
        titleSlug: "building-web-applications-with-php",
        status: "inactive",
        topics: 9,
        courseName: "PHP",
      },
    ],
    status: "inactive",
  },
  {
    title: "SQL",
    titleSlug: "sql",
    description:
      "SQL (Structured Query Language) is a domain-specific language used in programming and designed for managing data held in a relational database management system (RDBMS), or for stream processing in a relational data stream management system (RDSMS).",
    chapters: [
      {
        title: "SQL Basics",
        titleSlug: "sql-basics",
        status: "active",
        topics: 8,
        courseName: "SQL",
      },
      {
        title: "Advanced SQL Queries",
        titleSlug: "advanced-sql-queries",
        status: "active",
        topics: 7,
        courseName: "SQL",
      },
      {
        title: "Joins and Subqueries",
        titleSlug: "joins-and-subqueries",
        status: "active",
        topics: 6,
        courseName: "SQL",
      },
      {
        title: "Data Manipulation and Transactions",
        titleSlug: "data-manipulation-and-transactions",
        status: "active",
        topics: 9,
        courseName: "SQL",
      },
    ],
    status: "active",
  },
  {
    title: "Machine Learning",
    titleSlug: "machine-learning",
    description:
      "Machine learning is an application of artificial intelligence (AI) that provides systems the ability to automatically learn and improve from experience without being explicitly programmed. It focuses on the development of computer programs that can access data and use it to learn for themselves.",
    chapters: [
      {
        title: "Introduction to Machine Learning",
        titleSlug: "introduction-to-machine-learning",
        status: "active",
        topics: 9,
        courseName: "Machine Learning",
      },
      {
        title: "Supervised Learning",
        titleSlug: "supervised-learning",
        status: "active",
        topics: 8,
        courseName: "Machine Learning",
      },
      {
        title: "Unsupervised Learning",
        titleSlug: "unsupervised-learning",
        status: "active",
        topics: 7,
        courseName: "Machine Learning",
      },
      {
        title: "Neural Networks and Deep Learning",
        titleSlug: "neural-networks-and-deep-learning",
        status: "active",
        topics: 6,
        courseName: "Machine Learning",
      },
    ],
    status: "active",
  },
];

// Adding courses with their title slugs
export const chapters = [
  {
    title: "Introduction to JavaScript",
    titleSlug: "introduction-to-javascript",
    status: "active",
    topics: 8,
    courseName: "Javascript",
  },
  {
    title: "Data Types and Variables",
    titleSlug: "data-types-and-variables",
    status: "active",
    topics: 7,
    courseName: "Javascript",
  },
  {
    title: "Functions and Scope",
    titleSlug: "functions-and-scope",
    status: "active",
    topics: 6,
    courseName: "Javascript",
  },
  {
    title: "Objects and Prototypes",
    titleSlug: "objects-and-prototypes",
    status: "active",
    topics: 9,
    courseName: "Javascript",
  },
  {
    title: "ES6 Features",
    titleSlug: "es6-features",
    status: "active",
    topics: 7,
    courseName: "Javascript",
  },
  {
    title: "Python Basics",
    titleSlug: "python-basics",
    status: "active",
    topics: 9,
    courseName: "Python",
  },
  {
    title: "Functions and Modules",
    titleSlug: "functions-and-modules",
    status: "active",
    topics: 6,
    courseName: "Python",
  },
  {
    title: "Data Structures",
    titleSlug: "data-structures",
    status: "active",
    topics: 8,
    courseName: "Python",
  },
  {
    title: "Object-Oriented Programming",
    titleSlug: "object-oriented-programming",
    status: "active",
    topics: 7,
    courseName: "Python",
  },
  {
    title: "File Handling",
    titleSlug: "file-handling",
    status: "active",
    topics: 6,
    courseName: "Python",
  },
  {
    title: "Getting Started with React",
    titleSlug: "getting-started-with-react",
    status: "active",
    topics: 10,
    courseName: "React",
  },
  {
    title: "Components and Props",
    titleSlug: "components-and-props",
    status: "active",
    topics: 7,
    courseName: "React",
  },
  {
    title: "State and Lifecycle",
    titleSlug: "state-and-lifecycle",
    status: "active",
    topics: 8,
    courseName: "React",
  },
  {
    title: "Handling Events",
    titleSlug: "handling-events",
    status: "active",
    topics: 6,
    courseName: "React",
  },
  {
    title: "Introduction to Node.js",
    titleSlug: "introduction-to-nodejs",
    status: "active",
    topics: 6,
    courseName: "Node.js",
  },
  {
    title: "Modules and NPM",
    titleSlug: "modules-and-npm",
    status: "active",
    topics: 8,
    courseName: "Node.js",
  },
  {
    title: "Express.js Framework",
    titleSlug: "expressjs-framework",
    status: "active",
    topics: 9,
    courseName: "Node.js",
  },
  {
    title: "RESTful APIs",
    titleSlug: "restful-apis",
    status: "active",
    topics: 7,
    courseName: "Node.js",
  },
  {
    title: "Getting Started with Django",
    titleSlug: "getting-started-with-django",
    status: "inactive",
    topics: 7,
    courseName: "Django",
  },
  {
    title: "Models and Migrations",
    titleSlug: "models-and-migrations",
    status: "inactive",
    topics: 6,
    courseName: "Django",
  },
  {
    title: "Views and Templates",
    titleSlug: "views-and-templates",
    status: "inactive",
    topics: 8,
    courseName: "Django",
  },
  {
    title: "Forms and Admin Interface",
    titleSlug: "forms-and-admin-interface",
    status: "inactive",
    topics: 6,
    courseName: "Django",
  },
  {
    title: "Django REST Framework",
    titleSlug: "django-rest-framework",
    status: "inactive",
    topics: 9,
    courseName: "Django",
  },
  {
    title: "Introduction to Flask",
    titleSlug: "introduction-to-flask",
    status: "active",
    topics: 6,
    courseName: "Flask",
  },
  {
    title: "Routing and Views",
    titleSlug: "routing-and-views",
    status: "active",
    topics: 7,
    courseName: "Flask",
  },
  {
    title: "Templates and Forms",
    titleSlug: "templates-and-forms",
    status: "active",
    topics: 8,
    courseName: "Flask",
  },
  {
    title: "Database Integration",
    titleSlug: "database-integration",
    status: "active",
    topics: 9,
    courseName: "Flask",
  },
  {
    title: "Getting Started with Angular",
    titleSlug: "getting-started-with-angular",
    status: "inactive",
    topics: 7,
    courseName: "Angular",
  },
  {
    title: "Components and Directives",
    titleSlug: "components-and-directives",
    status: "inactive",
    topics: 8,
    courseName: "Angular",
  },
  {
    title: "Services and Dependency Injection",
    titleSlug: "services-and-dependency-injection",
    status: "inactive",
    topics: 9,
    courseName: "Angular",
  },
  {
    title: "Routing and Navigation",
    titleSlug: "routing-and-navigation",
    status: "inactive",
    topics: 6,
    courseName: "Angular",
  },
  {
    title: "Angular CLI and Testing",
    titleSlug: "angular-cli-and-testing",
    status: "inactive",
    topics: 6,
    courseName: "Angular",
  },
  {
    title: "Introduction to Vue.js",
    titleSlug: "introduction-to-vuejs",
    status: "active",
    topics: 8,
    courseName: "Vue.js",
  },
  {
    title: "Vue Components and Props",
    titleSlug: "vue-components-and-props",
    status: "active",
    topics: 7,
    courseName: "Vue.js",
  },
  {
    title: "Vue Router and Vuex",
    titleSlug: "vue-router-and-vuex",
    status: "active",
    topics: 9,
    courseName: "Vue.js",
  },
  {
    title: "Advanced Vue.js Concepts",
    titleSlug: "advanced-vuejs-concepts",
    status: "active",
    topics: 6,
    courseName: "Vue.js",
  },
  {
    title: "Java Basics",
    titleSlug: "java-basics",
    status: "active",
    topics: 10,
    courseName: "Java",
  },
  {
    title: "Object-Oriented Programming in Java",
    titleSlug: "object-oriented-programming-in-java",
    status: "active",
    topics: 8,
    courseName: "Java",
  },
  {
    title: "Collections Framework",
    titleSlug: "collections-framework",
    status: "active",
    topics: 9,
    courseName: "Java",
  },
  {
    title: "Concurrency in Java",
    titleSlug: "concurrency-in-java",
    status: "active",
    topics: 7,
    courseName: "Java",
  },
  {
    title: "Introduction to C#",
    titleSlug: "introduction-to-csharp",
    status: "inactive",
    topics: 8,
    courseName: "C#",
  },
  {
    title: "C# Basics",
    titleSlug: "csharp-basics",
    status: "inactive",
    topics: 7,
    courseName: "C#",
  },
  {
    title: "Advanced C# Programming",
    titleSlug: "advanced-csharp-programming",
    status: "inactive",
    topics: 9,
    courseName: "C#",
  },
  {
    title: "ASP.NET Core",
    titleSlug: "aspnet-core",
    status: "inactive",
    topics: 6,
    courseName: "C#",
  },
  {
    title: "Getting Started with Ruby on Rails",
    titleSlug: "getting-started-with-ruby-on-rails",
    status: "active",
    topics: 7,
    courseName: "Ruby on Rails",
  },
  {
    title: "Rails Models and Controllers",
    titleSlug: "rails-models-and-controllers",
    status: "active",
    topics: 8,
    courseName: "Ruby on Rails",
  },
  {
    title: "Views and Layouts in Rails",
    titleSlug: "views-and-layouts-in-rails",
    status: "active",
    topics: 9,
    courseName: "Ruby on Rails",
  },
  {
    title: "RESTful APIs with Rails",
    titleSlug: "restful-apis-with-rails",
    status: "active",
    topics: 6,
    courseName: "Ruby on Rails",
  },
  {
    title: "PHP Basics",
    titleSlug: "php-basics",
    status: "inactive",
    topics: 6,
    courseName: "PHP",
  },
  {
    title: "PHP Functions and Arrays",
    titleSlug: "php-functions-and-arrays",
    status: "inactive",
    topics: 7,
    courseName: "PHP",
  },
  {
    title: "MySQL Database Integration",
    titleSlug: "mysql-database-integration",
    status: "inactive",
    topics: 8,
    courseName: "PHP",
  },
  {
    title: "Building Web Applications with PHP",
    titleSlug: "building-web-applications-with-php",
    status: "inactive",
    topics: 9,
    courseName: "PHP",
  },
  {
    title: "SQL Basics",
    titleSlug: "sql-basics",
    status: "active",
    topics: 8,
    courseName: "SQL",
  },
  {
    title: "Advanced SQL Queries",
    titleSlug: "advanced-sql-queries",
    status: "active",
    topics: 7,
    courseName: "SQL",
  },
  {
    title: "Joins and Subqueries",
    titleSlug: "joins-and-subqueries",
    status: "active",
    topics: 6,
    courseName: "SQL",
  },
  {
    title: "Data Manipulation and Transactions",
    titleSlug: "data-manipulation-and-transactions",
    status: "active",
    topics: 9,
    courseName: "SQL",
  },
  {
    title: "Introduction to Machine Learning",
    titleSlug: "introduction-to-machine-learning",
    status: "active",
    topics: 9,
    courseName: "Machine Learning",
  },
  {
    title: "Supervised Learning",
    titleSlug: "supervised-learning",
    status: "active",
    topics: 8,
    courseName: "Machine Learning",
  },
  {
    title: "Unsupervised Learning",
    titleSlug: "unsupervised-learning",
    status: "active",
    topics: 7,
    courseName: "Machine Learning",
  },
  {
    title: "Neural Networks and Deep Learning",
    titleSlug: "neural-networks-and-deep-learning",
    status: "active",
    topics: 6,
    courseName: "Machine Learning",
  },
];

export default courses;
