const topics = [
  {
    title: "Introduction to Programming",
    titleSlug: "introduction-to-programming",
    status: "active",
    content: "<p>This is an introductory course on programming.</p>",
    chapterName: "Introduction to JavaScript",
    chapterNameSlug: "introduction-to-javascript",
    duration: "03 Hours",
  },
  {
    title: "Variables and Data Types",
    titleSlug: "variables-and-data-types",
    status: "active",
    content: "<p>Understanding variables and data types.</p>",
    chapterName: "Python Basics",
    chapterNameSlug: "python-basics",
    duration: "02 Hours",
  },
  {
    title: "Control Structures",
    titleSlug: "control-structures",
    status: "inactive",
    content: "<p>Learn about if-else, loops, and switch cases.</p>",
    chapterName: "Getting Started with React",
    chapterNameSlug: "getting-started-with-react",
    duration: "01 Day",
  },
  {
    title: "Functions and Methods",
    titleSlug: "functions-and-methods",
    status: "active",
    content: "<p>An introduction to functions and methods.</p>",
    chapterName: "Introduction to Node.js",
    chapterNameSlug: "introduction-to-node-js",
    duration: "02 Days",
  },
  {
    title: "Object-Oriented Programming",
    titleSlug: "object-oriented-programming",
    status: "inactive",
    content: "<p>Learn the basics of OOP.</p>",
    chapterName: "Getting Started with Django",
    chapterNameSlug: "getting-started-with-django",
    duration: "03 Days",
  },
  {
    title: "Inheritance and Polymorphism",
    titleSlug: "inheritance-and-polymorphism",
    status: "active",
    content: "<p>Dive into inheritance and polymorphism.</p>",
    chapterName: "Introduction to Flask",
    chapterNameSlug: "introduction-to-flask",
    duration: "04 Hours",
  },
  {
    title: "Data Structures",
    titleSlug: "data-structures",
    status: "inactive",
    content: "<p>Learn about arrays, linked lists, and other data structures.</p>",
    chapterName: "Getting Started with Angular",
    chapterNameSlug: "getting-started-with-angular",
    duration: "05 Hours",
  },
  {
    title: "Algorithms",
    titleSlug: "algorithms",
    status: "active",
    content: "<p>Introduction to algorithms and their complexity.</p>",
    chapterName: "Introduction to Vue.js",
    chapterNameSlug: "introduction-to-vue-js",
    duration: "03 Hours",
  },
  {
    title: "Database Management",
    titleSlug: "database-management",
    status: "inactive",
    content: "<p>Learn how to manage databases and SQL.</p>",
    chapterName: "Java Basics",
    chapterNameSlug: "java-basics",
    duration: "02 Days",
  },
  {
    title: "Web Development Basics",
    titleSlug: "web-development-basics",
    status: "active",
    content: "<p>Introduction to HTML, CSS, and JavaScript.</p>",
    chapterName: "Introduction to C#",
    chapterNameSlug: "introduction-to-c-sharp",
    duration: "01 Month",
  },
  {
    title: "Frontend Frameworks",
    titleSlug: "frontend-frameworks",
    status: "active",
    content: "<p>Learn about React, Angular, and Vue.</p>",
    chapterName: "Getting Started with Ruby on Rails",
    chapterNameSlug: "getting-started-with-ruby-on-rails",
    duration: "03 Weeks",
  },
  {
    title: "Backend Development",
    titleSlug: "backend-development",
    status: "inactive",
    content: "<p>Introduction to backend development with Node.js and Express.</p>",
    chapterName: "PHP Basics",
    chapterNameSlug: "php-basics",
    duration: "02 Weeks",
  },
  {
    title: "API Development",
    titleSlug: "api-development",
    status: "active",
    content: "<p>Learn how to create RESTful APIs.</p>",
    chapterName: "SQL Basics",
    chapterNameSlug: "sql-basics",
    duration: "01 Week",
  },
  {
    title: "Version Control with Git",
    titleSlug: "version-control-with-git",
    status: "active",
    content: "<p>Learn the basics of Git and GitHub.</p>",
    chapterName: "Introduction to Machine Learning",
    chapterNameSlug: "introduction-to-machine-learning",
    duration: "03 Hours",
  },
  {
    title: "DevOps Basics",
    titleSlug: "devops-basics",
    status: "inactive",
    content: "<p>Introduction to DevOps practices and tools.</p>",
    chapterName: "Data Types and Variables",
    chapterNameSlug: "data-types-and-variables",
    duration: "01 Month",
  },
];

export default topics;
